# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Edgaras Lisauskas
title: System Engineer / DevOps
email: edgaras.lisauskas@icloud.com
phone: 0037065268437

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  elisauskas
stackoverflow_username: "8727855"
linkedin_username: elisauskas

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, 
  
  my name's Edgaras and I'm a System Engineer at Wix.com. As well as administrating systems I also have experience building infrastructure and setting up CI/CD. I have worked at a number of companies gaining teamwork and leadership skills.

  Stack of technologies I am familiar with: 
  - Cloud Platforms: <mark>AWS</mark>, <mark>GCP</mark>
  - Operating Systems: <mark>Ubuntu</mark>, <mark>CentOS</mark>, <mark>OS X</mark>, <mark>Windows</mark>
  - Applications Platforms: <mark>Kubernetes</mark>, <mark>EKS</mark>, <mark>GKE</mark>, <mark>Docker</mark>, <mark>Docker Compose</mark>, <mark>OpenVZ</mark>
  - Container Image Registry: <mark>Docker Hub</mark>, <mark>ECR</mark>, <mark>GCR</mark>, <mark>Artifactory</mark>
  - Automation & Orchestration: <mark>Terraform</mark>, <mark>Atlantis</mark>, <mark>Packer</mark>, <mark>Chef</mark>
  - Continuous Integration & Delivery: <mark>GitLab CI</mark>, <mark>GitHub Actions</mark>, <mark>Jenkins</mark>, <mark>TeamCity</mark>
  - Source Code Management: <mark>GitLab</mark>, <mark>GitHub</mark>
  - Web Servers: <mark>Nginx</mark>, <mark>Apache</mark>
  - SSL: <mark>Let's Encrypt</mark>, <mark>ACM</mark>
  - Databases: <mark>Etcd</mark>, <mark>PostgreSQL</mark>, <mark>MySQL</mark>, <mark>ElasticSearch</mark>
  - Observability & Monitoring: <mark>Prometheus</mark>, <mark>Grafana</mark>, <mark>Zabbix</mark>
  - Service Discovery & Service Mesh: <mark>Consul</mark>
  - Distributed messaging: <mark>RabbitMQ</mark>, <mark>Kafka</mark>
  - Programming Languages: <mark>Bash</mark>, <mark>Python</mark>, <mark>Rust</mark>, <mark>Go</mark>
  - Secret Management: <mark>Vault</mark>
  - VPN: <mark>OpenVPN</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wix.com
        link: wix.com
        sub_title: System Engineer
        caption: May 2020 - Present
        quote: >
          Wix.com is a leading cloud-based development platform with millions of users worldwide, it makes easy for everyone to create a beautiful, professional web presence.
        description: | # this will include new lines to allow paragraphs
           Infrastructure as a code, administration of Kubernetes clusters and other infrastructure systems related components.
      
      - layout: left
        title: Shift4 Payments
        link: www.shift4.lt
        sub_title: DevOps Engineer
        caption: Jan 2018 - May 2020
        quote: >
          Shift4 Payments (NYSE: FOUR) is a leading provider of integrated payment processing and technology solutions, delivering a complete omnichannel ecosystem that extends beyond payments to include a wide range of commerce-enabling services.
        description: | # this will include new lines to allow paragraphs
          Maintenance of all infrastructure components and systems, CI/CD pipelines set up for the new projects and preparation of environments.
            - Migrated various kinds of projects from Jenkins to GitLab CI and decommissioned Jenkins.
            - Migrated services from AWS ElasticBeanstalk to AWS ECS.

      - layout: left
        title: Ruptela, UAB
        link: www.ruptela.lt
        sub_title: IT Systems Administrator
        caption: May 2016 - Jan 2018
        quote: >
          Ruptela develops and manufactures GPS tracking hardware, real-time tracking software and provides other related services.
        description: | # this will include new lines to allow paragraphs
          Administration of internal systems, maintenance of GPS tracking system infrastructure components, IT support.
            - Upgraded versions of all services related to GPS tracking system infrastructure in all locations worldwide.

      - layout: left
        title: Ruptela, UAB
        link: www.ruptela.lt
        sub_title: Senior Technical Support Engineer
        caption: Jan 2013 - May 2016
        quote: >
          Ruptela develops and manufactures GPS tracking hardware, real-time tracking software and provides other related services.
        description: | # this will include new lines to allow paragraphs
          Dedicated VIP clients support agent with 3rd level support responsibilities.
            - Supported migration of GPS tracking servers from one geographical location to another and migration (reconfiguration) of all GPS tracking devices. Cooperated with business analysts and developers, defined a mechanism for automating the whole reconfiguration process.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vilnius Tech
        link: www.vilniustech.lt
        caption: 2008 - 2012
        sub_title: BSc Telecommunications Engineering
        quote: >
          Vilnius Gediminas Technical University (VILNIUS TECH) is a leading higher education institution situated in Vilnius the capital of Lithuania. Established in 1956 VILNIUS TECH is one of the biggest research universities in country with a focus on technologies and engineering and strong emphasis on university-business cooperation.
      - layout: left
        title: Instituto Politécnico de Viana do Castelo
        link: www.ipvc.pt/en/
        caption: 2008 - 2012
        sub_title: BSc Engenharia Eletrónica e Redes de Computadores (Erasmus studies)
        quote: >
          The Polytechnic Institute of Viana do Castelo (IPVC) was founded in 1980. Is a regional institution, whose aims are a qualified human, cultural, scientific, technical and professional training, to carry out necessary research to accomplish its mission and to cooperate with the regional community of Alto-Minho, particularly with its productive and entrepreneurial sectors.
      - layout: left
        title: Lieporiai secondary school
        link: www.lieporiai.lt
        caption: 1996 - 2008
        sub_title: Secondary education

  - title: A Little Bit More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in systems administration and software engineering some of my other interests and hobbies are:
      - Repairing cars and motorcycles
      - Reading books
      - Playing football
      - Driving scenic roads and long walks while exploring nature or cities

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
