# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Edgaras Lisauskas
title: System Engineer / DevOps
email: edgaras.lisauskas@icloud.com
phone: 0037065268437

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  elisauskas
stackoverflow_username: "8727855"
linkedin_username: elisauskas

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Edgaras and I'm a System Engineer at Wix.com. As well as administrating systems I also have experience building infrastructure and setting up CI/CD. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Kubernetes</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wix.com
        link: wix.com
        sub_title: System Engineer
        caption: May 2020 - Present
        quote: >
          Infrastructure as a code, administration of Kubernetes clusters
        description: | # this will include new lines to allow paragraphs
            Text there 
      
      - layout: left
        title: Shift4 Payments
        link: www.shift4.lt
        sub_title: DevOps Engineer
        caption: Jan 2018 - May 2020
        quote: >
          CI/CD, systems administration, processes automation, scripting, infrastructure administration.
        description: | # this will include new lines to allow paragraphs
            Text there 

      - layout: left
        title: Ruptela, UAB
        link: www.ruptela.lt
        sub_title: IT Systems Administrator
        caption: May 2016 - Jan 2018
        quote: >
          Maintenance and administration of GPS tracking system and all related components built on various kind of technologies, as well as other internal systems administration tasks and 3rd level application support. 
        description: | # this will include new lines to allow paragraphs
            Text there

      - layout: left
        title: Ruptela, UAB
        link: www.ruptela.lt
        sub_title: Senior Technical Support Engineer
        caption: Jan 2013 - May 2016
        quote: >
          Technical support of hardware and software GPS tracking system products, systems administration. 
        description: | # this will include new lines to allow paragraphs
            Text there

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vilnius Tech
        caption: 2008 - 2012
        sub_title: BSc Telecommunications Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in systems administration and software engineering some of my other interests and hobbies are:
      - Repairing cars and motorcycles
      - Reading books
      - Playing football
      - Driving scenic roads and long walks while exploring nature or cities

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
