# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Edgaras Lisauskas
title: Site Reliability Engineer / Systems Engineer
email: edgaras.lisauskas@icloud.com
phone: 0037065268437

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  edgarasl

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi 👋, 
  
  I am a Site Reliability Engineer who is inspired by open-minded professionals and motivated by progress, efficiency, and results. 
  As well as administrating systems I also have experience defining infrastructure as a code, monitoring, and setting up CI/CD. 
  I have worked at a number of companies gaining teamwork and leadership skills, so would fit into Site Reliability Engineer, 
  Systems Architect or Cloud Architect/Consultant roles.

content:
  - title: Technologies Stack # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - <p style="font-style: italic;font-weight: bold;">Example realm:
        <mark style="background: #FFFFFF">Day to day</mark>,
        <mark style="background: #E0E0E0">Time to time</mark>,
        <mark style="background: #A0A0A0">A while ago not much</mark></p><br>
      - Cloud Platforms: 
        <mark style="background: #FFFFFF">AWS</mark>,
        <mark style="background: #E0E0E0">GCP</mark>
      - Amazon Web Services: 
        <mark style="background: #FFFFFF">IAM</mark>,
        <mark style="background: #FFFFFF">CloudTrail</mark>,
        <mark style="background: #FFFFFF">VPC</mark>,
        <mark style="background: #FFFFFF">EC2</mark>,
        <mark style="background: #FFFFFF">S3</mark>,
        <mark style="background: #FFFFFF">Lambda</mark>,
        <mark style="background: #FFFFFF">Route53</mark>,
        <mark style="background: #FFFFFF">EKS</mark>,
        <mark style="background: #E0E0E0">CloudFront</mark>,
        <mark style="background: #E0E0E0">CloudWatch</mark>,
        <mark style="background: #E0E0E0">ECS</mark>,
        <mark style="background: #E0E0E0">ECR</mark>,
        <mark style="background: #E0E0E0">ACM</mark>,
        <mark style="background: #A0A0A0">RDS</mark>
        <mark style="background: #A0A0A0">SQS</mark>,
        <mark style="background: #A0A0A0">SNS</mark>,
      - Operating Systems: 
        <mark style="background: #FFFFFF">Ubuntu</mark>,
        <mark style="background: #FFFFFF">CentOS</mark>,
        <mark style="background: #FFFFFF">OS X</mark>,
        <mark style="background: #E0E0E0">Windows</mark>
      - Applications Platforms: 
        <mark style="background: #FFFFFF">Kubernetes</mark>,
        <mark style="background: #FFFFFF">EKS</mark>,
        <mark style="background: #E0E0E0">GKE</mark>,
        <mark style="background: #E0E0E0">Docker</mark>,
        <mark style="background: #A0A0A0">Docker Compose</mark>,
        <mark style="background: #A0A0A0">OpenVZ</mark>
      - Container Image Registry: 
        <mark style="background: #E0E0E0">Docker Hub</mark>,
        <mark style="background: #E0E0E0">ECR</mark>,
        <mark style="background: #E0E0E0">GCR</mark>,
        <mark style="background: #E0E0E0">Artifactory</mark>
      - Automation & Orchestration: 
        <mark style="background: #FFFFFF">Terraform</mark>,
        <mark style="background: #E0E0E0">Atlantis</mark>,
        <mark style="background: #E0E0E0">Packer</mark>,
        <mark style="background: #E0E0E0">Kustomize</mark>,
        <mark style="background: #E0E0E0">Chef</mark>
      - Continuous Integration & Delivery: 
        <mark style="background: #E0E0E0">GitLab CI</mark>,
        <mark style="background: #E0E0E0">GitHub Actions</mark>,
        <mark style="background: #E0E0E0">TeamCity</mark>,
        <mark style="background: #A0A0A0">Jenkins</mark>
      - Source Code Management: 
        <mark style="background: #FFFFFF">GitLab</mark>,
        <mark style="background: #FFFFFF">GitHub</mark>
      - Web Servers: 
        <mark style="background: #E0E0E0">Nginx</mark>,
        <mark style="background: #A0A0A0">Apache</mark>
      - SSL: 
        <mark style="background: #E0E0E0">Let's Encrypt</mark>,
        <mark style="background: #E0E0E0">ACM</mark>
      - Databases: <mark style="background: #FFFFFF">Etcd</mark>,
        <mark style="background: #E0E0E0">PostgreSQL</mark>,
        <mark style="background: #E0E0E0">MySQL</mark>,
        <mark style="background: #A0A0A0">ElasticSearch</mark>
      - Observability & Monitoring: 
        <mark style="background: #E0E0E0">Prometheus</mark>,
        <mark style="background: #E0E0E0">VictoriaMetrics, VMalert, VMagent</mark>,
        <mark style="background: #E0E0E0">Grafana</mark>,
        <mark style="background: #E0E0E0">OpsGenie</mark>,
        <mark style="background: #E0E0E0">Yet Another CloudWatch Exporter</mark>,
        <mark style="background: #A0A0A0">Zabbix</mark>
      - Service Discovery & Service Mesh: 
        <mark style="background: #FFFFFF">Consul</mark>
      - Distributed messaging: 
        <mark style="background: #E0E0E0">RabbitMQ</mark>,
        <mark style="background: #E0E0E0">Kafka</mark>
      - Programming Languages: 
        <mark style="background: #FFFFFF">Bash</mark>,
        <mark style="background: #E0E0E0">Python</mark>,
        <mark style="background: #A0A0A0">Rust</mark>,
        <mark style="background: #A0A0A0">Go</mark>
      - Secret Management: 
        <mark style="background: #E0E0E0">Vault</mark>
      - Project Management & Knowledge Base:
        <mark style="background: #FFFFFF">Monday</mark>
        <mark style="background: #FFFFFF">Jira</mark>
        <mark style="background: #E0E0E0">Confluence</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Workato
        link: www.workato.com
        sub_title: Senior Site Reliability Engineer
        caption: Sep 2022 - Present
        quote: >
          Workato, a leader in Gartner MQ, is more than an iPaaS. It's an Intelligent Automation platform that can be used by both Business and IT.
        description: | # this will include new lines to allow paragraphs
          Infrastructure as a code, SLIs/SLOs, being embedded in the development team, incidents response.
            - Documented and created Yet Another CloudWatch Exporter implementation for global codified alerts solution of AWS managed services.
            - Cleaned up AWS accounts from part of unused resources and scaled-down part of over-provisioned resources.
            - Created and documented initial processes for ad-hoc task management and production changes.
          
      - layout: left
        title: Wix.com
        link: wix.com
        sub_title: System Engineer
        caption: May 2020 - Sep 2022
        quote: >
          Wix.com is a leading cloud-based development platform with millions of users worldwide, it makes easy for everyone to create a beautiful, professional web presence.
        description: | # this will include new lines to allow paragraphs
          Infrastructure as a code, administration of Kubernetes clusters and other infrastructure systems related components on Amazon Web Services (AWS) and Google Cloud Platform (GCP).
            - Migrated k8s clusters through multiple kOps versions, the process required major terraform version upgrade as well and that increased project complexity.
            - Took my part in the new datacenter buildout process on AWS, created internal DNS, ZooKeeper, Consul and EKS clusters via Terraform by utilising its modules feature.
            - Created GKE clusters in different regions and validated them to be production ready.
      
      - layout: left
        title: Shift4 Payments
        link: www.shift4.lt
        sub_title: DevOps Engineer
        caption: Jan 2018 - May 2020
        quote: >
          Shift4 Payments (NYSE: FOUR) is a leading provider of integrated payment processing and technology solutions, delivering a complete omnichannel ecosystem that extends beyond payments to include a wide range of commerce-enabling services.
        description: | # this will include new lines to allow paragraphs
          Maintenance of all infrastructure components and systems, CI/CD pipelines set up for the new projects and preparation of environments.
            - Migrated various kinds of projects from Jenkins to GitLab CI and decommissioned Jenkins.
            - Migrated services from AWS ElasticBeanstalk to AWS ECS.

      - layout: left
        title: Ruptela, UAB
        link: www.ruptela.lt
        sub_title: IT Systems Administrator
        caption: May 2016 - Jan 2018
        quote: >
          Ruptela develops and manufactures GPS tracking hardware, real-time tracking software and provides other related services.
        description: | # this will include new lines to allow paragraphs
          Administration of internal systems, maintenance of GPS tracking system infrastructure components, IT support.
            - Upgraded versions of all services related to GPS tracking system infrastructure in all locations worldwide.

      - layout: left
        title: Ruptela, UAB
        link: www.ruptela.lt
        sub_title: Senior Technical Support Engineer
        caption: Jan 2013 - May 2016
        quote: >
          Ruptela develops and manufactures GPS tracking hardware, real-time tracking software and provides other related services.
        description: | # this will include new lines to allow paragraphs
          Dedicated VIP clients support agent with 3rd level support responsibilities.
            - Supported migration of GPS tracking servers from one geographical location to another and migration (reconfiguration) of all GPS tracking devices. Cooperated with business analysts and developers, defined a mechanism for automating the whole reconfiguration process.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vilnius Tech
        link: www.vilniustech.lt
        caption: 2008 - 2012
        sub_title: BSc Telecommunications Engineering
        quote: >
          Vilnius Gediminas Technical University (VILNIUS TECH) is a leading higher education institution situated in Vilnius the capital of Lithuania. Established in 1956 VILNIUS TECH is one of the biggest research universities in country with a focus on technologies and engineering and strong emphasis on university-business cooperation.
      - layout: left
        title: Instituto Politécnico de Viana do Castelo
        link: www.ipvc.pt/en/
        caption: 2010 - 2011
        sub_title: BSc Engenharia Eletrónica e Redes de Computadores (Erasmus studies)
        quote: >
          The Polytechnic Institute of Viana do Castelo (IPVC) was founded in 1980. Is a regional institution, whose aims are a qualified human, cultural, scientific, technical and professional training, to carry out necessary research to accomplish its mission and to cooperate with the regional community of Alto-Minho, particularly with its productive and entrepreneurial sectors.
      - layout: left
        title: Lieporiai secondary school
        link: www.lieporiai.lt
        caption: 1996 - 2008
        sub_title: Secondary education

  - title: A Little Bit More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in systems administration and software engineering some of my other interests and hobbies are:
      - Repairing cars and motorcycles
      - Reading books
      - Playing football
      - Driving scenic roads and long walks while exploring nature or cities
      
      **The Blueprint Blues** (haiku) by myself  
      _Decisions were made,_  
      _Presentation was given,_   
      _Architect's role played._  

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
